package pt.psoft.g1.psoftg1.readermanagement.services;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.web.multipart.MultipartFile;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("UpdateReaderRequest – Lombok data behavior and field consistency")
class UpdateReaderRequestTest {

    // SUT inside test for full visibility
    static class SUT extends UpdateReaderRequest { }

    @Test
    @DisplayName("Default constructor initializes fields to null/false as expected")
    void defaultConstructor_initialValues() {
        var sut = new SUT();

        assertNull(sut.getNumber());
        assertNull(sut.getUsername());
        assertNull(sut.getPassword());
        assertNull(sut.getFullName());
        assertNull(sut.getBirthDate());
        assertNull(sut.getPhoneNumber());
        assertNull(sut.getInterestList());
        assertNull(sut.getPhoto());

        // Booleans default to false
        assertFalse(sut.getMarketing());
        assertFalse(sut.getThirdParty());
    }

    @Test
    @DisplayName("All setters and getters work correctly for basic types")
    void setters_getters_basicFields() {
        var sut = new SUT();
        sut.setNumber("2025/001");
        sut.setUsername("reader@example.com");
        sut.setPassword("secret123");
        sut.setPhoto(Mockito.mock(MultipartFile.class));
        sut.setInterestList(List.of("Fiction", "Horror"));

        assertEquals("2025/001", sut.getNumber());
        assertEquals("reader@example.com", sut.getUsername());
        assertEquals("secret123", sut.getPassword());
        assertEquals(List.of("Fiction", "Horror"), sut.getInterestList());
        assertNotNull(sut.getPhoto());
    }

    @Test
    @DisplayName("Can modify and reassign interest list safely (alias behavior)")
    void interestList_aliasBehavior() {
        var sut = new SUT();
        List<String> interests = new ArrayList<>(List.of("Action"));
        sut.setInterestList(interests);

        assertSame(interests, sut.getInterestList());

        interests.add("Drama");
        assertEquals(2, sut.getInterestList().size());
        assertTrue(sut.getInterestList().contains("Drama"));
    }

    @Test
    @DisplayName("Boolean getters reflect internal field state")
    void booleanGetters_reflectState() {
        var sut = new SUT();

        // Initially false
        assertFalse(sut.getMarketing());
        assertFalse(sut.getThirdParty());

        // Using reflection to set internal booleans (since Lombok doesn’t auto-generate setters for primitive-only fields)
        try {
            var marketingField = UpdateReaderRequest.class.getDeclaredField("marketing");
            marketingField.setAccessible(true);
            marketingField.setBoolean(sut, true);

            var thirdPartyField = UpdateReaderRequest.class.getDeclaredField("thirdParty");
            thirdPartyField.setAccessible(true);
            thirdPartyField.setBoolean(sut, true);
        } catch (Exception e) {
            fail("Reflection setup failed: " + e.getMessage());
        }

        assertTrue(sut.getMarketing());
        assertTrue(sut.getThirdParty());
    }

    @Test
    @DisplayName("toString(), equals(), and hashCode() generated by Lombok work as expected")
    void lombokGeneratedMethods_work() {
        var a = new SUT();
        a.setNumber("N1");
        a.setUsername("a@b.com");

        var b = new SUT();
        b.setNumber("N1");
        b.setUsername("a@b.com");

        assertEquals(a, b);
        assertEquals(a.hashCode(), b.hashCode());
        assertTrue(a.toString().contains("a@b.com"));
    }

    @Test
    @DisplayName("Nullable fields can safely accept null values")
    void nullableFields_acceptNulls() {
        var sut = new SUT();

        sut.setUsername(null);
        sut.setPassword(null);
        sut.setInterestList(null);
        sut.setPhoto(null);

        assertNull(sut.getUsername());
        assertNull(sut.getPassword());
        assertNull(sut.getInterestList());
        assertNull(sut.getPhoto());
    }
}
